"""Versioned contracts for retained and live timeline consumers.

The contracts deliberately describe product behaviour instead of mirroring an
upstream implementation or transport-specific payload.  A browser can receive
the same frames through an initial NDJSON snapshot and a resumable SSE stream.
"""

from packages.contracts.timeline.models import (
    RealtimePolicy,
    TimelineActivityControlOption,
    TimelineApplicationPinSnapshot,
    TimelineApplicationWorkflowSubject,
    TimelineBooleanControl,
    TimelineCapabilityDescriptor,
    TimelineControlOption,
    TimelineControlSurface,
    TimelineCoverage,
    TimelineCoverageSourceAvailability,
    TimelineCursor,
    TimelineEvent,
    TimelineFacetControl,
    TimelineFilters,
    TimelineIncidentSubject,
    TimelineInventoryLocatorSubject,
    TimelineLegendControl,
    TimelineLensZoomOption,
    TimelineLiveSessionPolicy,
    TimelineOverview,
    TimelineOverviewActivityFacet,
    TimelineOverviewBucket,
    TimelineOverviewFacets,
    TimelineOverviewKindFacet,
    TimelinePin,
    TimelinePinApplicationTarget,
    TimelinePinMutation,
    TimelinePinnedApplicationSubject,
    TimelinePinnedResourceSubject,
    TimelinePinResourceTarget,
    TimelinePinsControl,
    TimelinePinSet,
    TimelinePinSubject,
    TimelinePinTarget,
    TimelinePinUpsertRequest,
    TimelineQuery,
    TimelineQueryBounds,
    TimelineRangePreset,
    TimelineReconnectPolicy,
    TimelineResourceSubject,
    TimelineSource,
    TimelineStreamFrame,
    TimelineSubject,
    TimelineWindow,
)
from packages.contracts.timeline.requests import (
    TimelineOverviewRequest,
    TimelineSnapshotRequest,
    TimelineStreamRequest,
)

__all__ = [
    "RealtimePolicy",
    "TimelineReconnectPolicy",
    "TimelineLiveSessionPolicy",
    "TimelineCapabilityDescriptor",
    "TimelineControlOption",
    "TimelineActivityControlOption",
    "TimelineApplicationPinSnapshot",
    "TimelineBooleanControl",
    "TimelineControlSurface",
    "TimelineFacetControl",
    "TimelineRangePreset",
    "TimelineLensZoomOption",
    "TimelineLegendControl",
    "TimelinePinsControl",
    "TimelinePin",
    "TimelinePinApplicationTarget",
    "TimelinePinMutation",
    "TimelinePinResourceTarget",
    "TimelinePinSet",
    "TimelinePinTarget",
    "TimelinePinUpsertRequest",
    "TimelinePinSubject",
    "TimelinePinnedApplicationSubject",
    "TimelinePinnedResourceSubject",
    "TimelineCoverage",
    "TimelineCoverageSourceAvailability",
    "TimelineCursor",
    "TimelineEvent",
    "TimelineFilters",
    "TimelineApplicationWorkflowSubject",
    "TimelineIncidentSubject",
    "TimelineInventoryLocatorSubject",
    "TimelineQuery",
    "TimelineQueryBounds",
    "TimelineOverview",
    "TimelineOverviewBucket",
    "TimelineOverviewActivityFacet",
    "TimelineOverviewKindFacet",
    "TimelineOverviewFacets",
    "TimelineResourceSubject",
    "TimelineSource",
    "TimelineSnapshotRequest",
    "TimelineOverviewRequest",
    "TimelineStreamRequest",
    "TimelineStreamFrame",
    "TimelineSubject",
    "TimelineWindow",
]
