/**
 * Reader-facing data contract inventory for every top-level product surface.
 *
 * This is deliberately executable TypeScript rather than a prose checklist:
 * tests require every shell surface, every dynamic feed, its canonical
 * backend path, authorization scope, transport, and fallback policy.
 */
export const SURFACE_IDS = [
  "home",
  "resources",
  "connect",
  "deploy",
  "issues",
  "timeline",
  "checks",
  "cost",
  "alerts",
  "ai",
  "settings",
] as const;

export type ProductSurfaceId = typeof SURFACE_IDS[number];

export type FeedTransport =
  | "sse-snapshot"
  | "sse-delta"
  | "websocket-snapshot-delta"
  | "bounded-poll"
  | "read-on-open"
  | "mutation-response";

export interface SurfaceDataContract {
  id: string;
  endpoint: string;
  transport: FeedTransport;
  /** Null means event-driven or intentionally read only on entry/user action. */
  maximumRefreshMs: number | null;
  authorization: "session" | "workspace" | "cluster" | "resource" | "service-admin";
  fallback: "http-last-known-good" | "resnapshot-cursor" | "honest-unavailable" | "none";
  fieldGroups: readonly string[];
}

export interface SurfaceContract {
  id: ProductSurfaceId;
  feeds: readonly SurfaceDataContract[];
}

/** Shell-owned singleton reads shared by every surface. */
export const SHELL_DATA_CONTRACTS: readonly SurfaceDataContract[] = [
  {
    id: "session",
    endpoint: "/auth/session",
    transport: "read-on-open",
    maximumRefreshMs: null,
    authorization: "session",
    fallback: "honest-unavailable",
    fieldGroups: ["identity", "workspace", "roles", "logout-capability"],
  },
  {
    id: "session-login",
    endpoint: "/auth/login",
    transport: "mutation-response",
    maximumRefreshMs: null,
    authorization: "session",
    fallback: "none",
    fieldGroups: ["identity", "session", "workspace", "roles"],
  },
  {
    id: "session-logout",
    endpoint: "/auth/logout",
    transport: "mutation-response",
    maximumRefreshMs: null,
    authorization: "session",
    fallback: "none",
    fieldGroups: ["session-revocation"],
  },
  {
    id: "cluster-catalog",
    endpoint: "/clusters",
    transport: "read-on-open",
    maximumRefreshMs: null,
    authorization: "workspace",
    fallback: "honest-unavailable",
    fieldGroups: ["cluster-identity", "connection", "observation", "capacity"],
  },
  {
    id: "cluster-unregister",
    endpoint: "/clusters/{cluster_id}",
    transport: "mutation-response",
    maximumRefreshMs: null,
    authorization: "cluster",
    fallback: "none",
    fieldGroups: ["uninstall-stage", "command", "cleanup", "residual-resources"],
  },
] as const;

export const REALTIME_CONTRACT_MATRIX: readonly SurfaceContract[] = [
  {
    id: "home",
    feeds: [
      {
        id: "fleet-summary",
        endpoint: "/fleet/events",
        transport: "sse-snapshot",
        maximumRefreshMs: 10_000,
        authorization: "workspace",
        fallback: "http-last-known-good",
        fieldGroups: ["cluster-health", "capacity", "usage", "incident-counts", "workflow-counts"],
      },
      {
        id: "fleet-summary-http-fallback",
        endpoint: "/fleet/summary",
        transport: "bounded-poll",
        maximumRefreshMs: 10_000,
        authorization: "workspace",
        fallback: "http-last-known-good",
        fieldGroups: ["cluster-health", "capacity", "usage", "incident-counts", "workflow-counts"],
      },
      {
        id: "home-issues",
        endpoint: "/dashboard/rca/issues",
        transport: "bounded-poll",
        maximumRefreshMs: 10_000,
        authorization: "cluster",
        fallback: "http-last-known-good",
        fieldGroups: ["incident-identity", "severity", "status", "resource-subject"],
      },
      {
        id: "home-applications",
        endpoint: "/applications",
        transport: "bounded-poll",
        maximumRefreshMs: 15_000,
        authorization: "workspace",
        fallback: "http-last-known-good",
        fieldGroups: ["repository", "delivery", "health", "workflow"],
      },
      {
        id: "home-timeline",
        endpoint: "/timeline/stream",
        transport: "sse-delta",
        maximumRefreshMs: null,
        authorization: "cluster",
        fallback: "resnapshot-cursor",
        fieldGroups: ["events", "severity", "coverage", "activity"],
      },
      {
        id: "home-timeline-capabilities",
        endpoint: "/timeline/capabilities",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "honest-unavailable",
        fieldGroups: ["source-mode", "scope-limit", "stream-policy", "controls"],
      },
      {
        id: "home-timeline-snapshot",
        endpoint: "/timeline/snapshots",
        transport: "sse-snapshot",
        maximumRefreshMs: null,
        authorization: "cluster",
        fallback: "resnapshot-cursor",
        fieldGroups: ["events", "coverage", "cursor", "policy"],
      },
      {
        id: "home-namespace-facets",
        endpoint: "/filter-facets",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "cluster",
        fallback: "honest-unavailable",
        fieldGroups: ["namespace", "pod-count"],
      },
      {
        id: "home-cost",
        endpoint: "/cost/overview",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "cluster",
        fallback: "honest-unavailable",
        fieldGroups: ["availability", "reason-codes"],
      },
      {
        id: "home-cluster-node-summary",
        endpoint: "/clusters/{cluster_id}/nodes/summary",
        transport: "bounded-poll",
        maximumRefreshMs: 5_000,
        authorization: "cluster",
        fallback: "http-last-known-good",
        fieldGroups: ["node-readiness", "pod-placement", "resource-usage", "freshness"],
      },
      {
        id: "home-cluster-summary",
        endpoint: "/clusters/{cluster_id}/summary",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "cluster",
        fallback: "honest-unavailable",
        fieldGroups: ["workload-health", "incidents", "events", "usage", "freshness"],
      },
      {
        id: "home-node-pods-summary",
        endpoint: "/clusters/{cluster_id}/nodes/{node_name}/pods/summary",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "cluster",
        fallback: "honest-unavailable",
        fieldGroups: ["pod-placement", "status", "health", "freshness"],
      },
    ],
  },
  {
    id: "resources",
    feeds: [
      {
        id: "resource-live",
        endpoint: "/live/browser",
        transport: "websocket-snapshot-delta",
        maximumRefreshMs: null,
        authorization: "cluster",
        fallback: "http-last-known-good",
        fieldGroups: ["resource-delta", "summary", "connection-freshness"],
      },
      {
        id: "resource-node-summary",
        endpoint: "/clusters/{cluster_id}/nodes/summary",
        transport: "bounded-poll",
        maximumRefreshMs: 5_000,
        authorization: "cluster",
        fallback: "http-last-known-good",
        fieldGroups: ["node-readiness", "pod-capacity", "resource-usage", "freshness"],
      },
      {
        id: "resource-inventory",
        endpoint: "/clusters/{cluster_id}/inventory/resources",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "cluster",
        fallback: "honest-unavailable",
        fieldGroups: ["identity", "namespace", "status", "summary"],
      },
      {
        id: "resource-service-inventory",
        endpoint: "/clusters/{cluster_id}/inventory/services",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "cluster",
        fallback: "honest-unavailable",
        fieldGroups: ["identity", "namespace", "type", "selectors"],
      },
      {
        id: "resource-workload-inventory",
        endpoint: "/clusters/{cluster_id}/inventory/workloads",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "cluster",
        fallback: "honest-unavailable",
        fieldGroups: ["identity", "namespace", "kind", "replicas", "status"],
      },
      {
        id: "resource-inventory-summary",
        endpoint: "/clusters/{cluster_id}/inventory/summary",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "cluster",
        fallback: "http-last-known-good",
        fieldGroups: ["resource-counts", "namespace-counts", "coverage", "observed-at"],
      },
      {
        id: "resource-detail",
        endpoint: "/clusters/{cluster_id}/inventory/resource-detail",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "resource",
        fallback: "honest-unavailable",
        fieldGroups: ["identity", "summary", "conditions", "events", "related-resources"],
      },
      {
        id: "workload-detail",
        endpoint: "/workloads/{kind}/{namespace}/{name}",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "resource",
        fallback: "honest-unavailable",
        fieldGroups: ["replicas", "health", "labels", "pods", "freshness"],
      },
      {
        id: "resource-usage-series",
        endpoint: "/clusters/{cluster_id}/usage",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "resource",
        fallback: "honest-unavailable",
        fieldGroups: ["cpu", "memory", "sampled-at", "coverage"],
      },
      {
        id: "physical-topology",
        endpoint: "/topology",
        transport: "bounded-poll",
        maximumRefreshMs: 60_000,
        authorization: "cluster",
        fallback: "http-last-known-good",
        fieldGroups: ["nodes", "pods", "placement", "coverage"],
      },
      {
        id: "relation-topology",
        endpoint: "/topology",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "cluster",
        fallback: "honest-unavailable",
        fieldGroups: ["services", "workloads", "relationships", "coverage"],
      },
      {
        id: "traffic",
        endpoint: "/traffic/flows",
        transport: "bounded-poll",
        maximumRefreshMs: 10_000,
        authorization: "cluster",
        fallback: "http-last-known-good",
        fieldGroups: ["source", "target", "connections", "verdict", "coverage"],
      },
      {
        id: "resource-repositories",
        endpoint: "/applications",
        transport: "bounded-poll",
        maximumRefreshMs: 15_000,
        authorization: "workspace",
        fallback: "http-last-known-good",
        fieldGroups: ["repository", "application", "delivery", "health"],
      },
      {
        id: "resource-node-aliases",
        endpoint: "/clusters/{cluster_id}/nodes/aliases",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "cluster",
        fallback: "honest-unavailable",
        fieldGroups: ["node", "alias", "revision"],
      },
      {
        id: "resource-node-alias-update",
        endpoint: "/clusters/{cluster_id}/nodes/{node_name}/alias",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "resource",
        fallback: "none",
        fieldGroups: ["node", "alias", "revision"],
      },
      {
        id: "resource-agent-debug-query",
        endpoint: "/agent/debug/query",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "resource",
        fallback: "none",
        fieldGroups: ["query", "result", "coverage", "observed-at"],
      },
      {
        id: "resource-config-references",
        endpoint: "/clusters/{cluster_id}/config-references",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "resource",
        fallback: "honest-unavailable",
        fieldGroups: ["config-map", "secret", "consumer", "key-count"],
      },
      {
        id: "resource-rbac-subject",
        endpoint: "/rbac/subject/{kind}/{namespace}/{name}",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "resource",
        fallback: "honest-unavailable",
        fieldGroups: ["roles", "bindings", "rules", "coverage"],
      },
      {
        id: "resource-rbac-global-subject",
        endpoint: "/rbac/subject/{kind}/{name}",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "resource",
        fallback: "honest-unavailable",
        fieldGroups: ["roles", "bindings", "rules", "coverage"],
      },
      {
        id: "resource-rbac-role",
        endpoint: "/rbac/role/{kind}/{namespace}/{name}",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "resource",
        fallback: "honest-unavailable",
        fieldGroups: ["subjects", "bindings", "rules", "coverage"],
      },
      {
        id: "resource-rbac-namespace",
        endpoint: "/rbac/namespace/{namespace}",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "resource",
        fallback: "honest-unavailable",
        fieldGroups: ["service-accounts", "roles", "bindings", "coverage"],
      },
      {
        id: "resource-manifest-source",
        endpoint: "/resource-manifests/{resource_id}",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "resource",
        fallback: "honest-unavailable",
        fieldGroups: ["git-source", "content-sha", "repository", "write-capability"],
      },
      {
        id: "resource-manifest-preview",
        endpoint: "/resource-manifests/{resource_id}/preview",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "resource",
        fallback: "none",
        fieldGroups: ["desired-sha", "diff", "validation", "approval"],
      },
      {
        id: "resource-manifest-approval",
        endpoint: "/resource-manifests/{resource_id}/approve",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "resource",
        fallback: "none",
        fieldGroups: ["approval", "revision", "desired-sha"],
      },
      {
        id: "resource-manifest-apply",
        endpoint: "/resource-manifests/{resource_id}/apply",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "resource",
        fallback: "none",
        fieldGroups: ["command", "approval", "source-revision"],
      },
      {
        id: "approval-grant",
        endpoint: "/approvals/{approval_id}/grant",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "resource",
        fallback: "none",
        fieldGroups: ["approval", "decision", "audit"],
      },
      {
        id: "approval-reject",
        endpoint: "/approvals/{approval_id}/reject",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "resource",
        fallback: "none",
        fieldGroups: ["approval", "decision", "audit"],
      },
      {
        id: "resource-command-status",
        endpoint: "/commands/{command_id}",
        transport: "bounded-poll",
        maximumRefreshMs: 1_500,
        authorization: "resource",
        fallback: "http-last-known-good",
        fieldGroups: ["state", "reason-code", "result", "audit"],
      },
    ],
  },
  {
    id: "connect",
    feeds: [
      {
        id: "cluster-registration",
        endpoint: "/clusters/{cluster_id}/connection-status",
        transport: "bounded-poll",
        maximumRefreshMs: 3_000,
        authorization: "cluster",
        fallback: "honest-unavailable",
        fieldGroups: ["stage", "status", "install-expiry", "first-inventory"],
      },
      {
        id: "repository-registration",
        endpoint: "/repositories/connection-status",
        transport: "bounded-poll",
        maximumRefreshMs: 3_000,
        authorization: "workspace",
        fallback: "honest-unavailable",
        fieldGroups: ["repository", "branch", "manifest-path", "connection-status"],
      },
      {
        id: "connection-inventory-readiness",
        endpoint: "/clusters/{cluster_id}/inventory/summary",
        transport: "bounded-poll",
        maximumRefreshMs: 3_000,
        authorization: "cluster",
        fallback: "honest-unavailable",
        fieldGroups: ["first-inventory", "resource-counts", "coverage"],
      },
      {
        id: "connection-usage-readiness",
        endpoint: "/clusters/{cluster_id}/usage",
        transport: "bounded-poll",
        maximumRefreshMs: 3_000,
        authorization: "cluster",
        fallback: "honest-unavailable",
        fieldGroups: ["first-sample", "nodes", "pods", "sampled-at"],
      },
      {
        id: "provider-catalog",
        endpoint: "/providers/catalog",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "honest-unavailable",
        fieldGroups: ["provider", "requirements", "capabilities"],
      },
      {
        id: "provider-discovery",
        endpoint: "/providers/cluster-discovery",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "honest-unavailable",
        fieldGroups: ["provider", "candidate", "region", "identity"],
      },
      {
        id: "repository-probe",
        endpoint: "/repositories/discovery/probe",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "none",
        fieldGroups: ["repository", "provider", "default-branch", "access"],
      },
      {
        id: "repository-branches",
        endpoint: "/repositories/discovery/branches",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "honest-unavailable",
        fieldGroups: ["branch", "default", "revision"],
      },
      {
        id: "repository-manifests",
        endpoint: "/repositories/discovery/manifests",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "honest-unavailable",
        fieldGroups: ["path", "kind", "application-candidate"],
      },
      {
        id: "repository-validation",
        endpoint: "/repositories/discovery/validate",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "none",
        fieldGroups: ["valid", "errors", "warnings", "resolved-source"],
      },
      {
        id: "cluster-preflight",
        endpoint: "/targets/preflight",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "none",
        fieldGroups: ["provider", "identity", "policy", "validation"],
      },
      {
        id: "cluster-registration-command",
        endpoint: "/targets",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "none",
        fieldGroups: ["cluster", "install-command", "expiry", "registration"],
      },
      {
        id: "cluster-connect",
        endpoint: "/clusters/connect",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "none",
        fieldGroups: ["cluster", "provider", "install-command", "expiry"],
      },
      {
        id: "cluster-connect-state",
        endpoint: "/clusters/{cluster_id}/connection",
        transport: "bounded-poll",
        maximumRefreshMs: 3_000,
        authorization: "cluster",
        fallback: "honest-unavailable",
        fieldGroups: ["stage", "status", "failure", "observed-at"],
      },
      {
        id: "cluster-connect-command-reissue",
        endpoint: "/clusters/{cluster_id}/connect-command",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "cluster",
        fallback: "none",
        fieldGroups: ["install-command", "expiry", "registration"],
      },
      {
        id: "application-connect-preview",
        endpoint: "/applications/connect/preview",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "none",
        fieldGroups: ["repository", "desired", "live", "conflicts"],
      },
      {
        id: "application-connect",
        endpoint: "/applications/connect",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "none",
        fieldGroups: ["application", "repository", "target", "validation"],
      },
      {
        id: "repository-catalog",
        endpoint: "/repositories",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "honest-unavailable",
        fieldGroups: ["repository", "provider", "credential", "connection"],
      },
      {
        id: "repository-disconnect",
        endpoint: "/repositories/disconnect",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "none",
        fieldGroups: ["repository", "disconnection", "affected-applications"],
      },
      {
        id: "github-app-config",
        endpoint: "/integrations/github/app/config",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "honest-unavailable",
        fieldGroups: ["configured", "slug", "install-capability", "uninstall-result"],
      },
      {
        id: "github-app-install-url",
        endpoint: "/integrations/github/app/install-url",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "honest-unavailable",
        fieldGroups: ["installation-url", "state"],
      },
      {
        id: "github-app-manifest",
        endpoint: "/integrations/github/app/manifest",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "honest-unavailable",
        fieldGroups: ["action-url", "manifest", "state"],
      },
      {
        id: "github-app-installation-verify",
        endpoint: "/integrations/github/app/installations/{installation_id}/verify",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "none",
        fieldGroups: ["repository-match", "write-capability", "permissions"],
      },
    ],
  },
  {
    id: "deploy",
    feeds: [
      {
        id: "applications",
        endpoint: "/applications",
        transport: "bounded-poll",
        maximumRefreshMs: 15_000,
        authorization: "workspace",
        fallback: "http-last-known-good",
        fieldGroups: ["application", "repository", "health", "delivery"],
      },
      {
        id: "workflow-runs",
        endpoint: "/applications/{application_id}/runs",
        transport: "bounded-poll",
        maximumRefreshMs: 15_000,
        authorization: "workspace",
        fallback: "http-last-known-good",
        fieldGroups: ["run", "steps", "gate", "command", "commit"],
      },
      {
        id: "helm-releases",
        endpoint: "/helm/releases",
        transport: "bounded-poll",
        maximumRefreshMs: 60_000,
        authorization: "cluster",
        fallback: "http-last-known-good",
        fieldGroups: ["release", "chart", "revision", "status", "coverage"],
      },
      {
        id: "application-detail",
        endpoint: "/applications/{application_id}",
        transport: "bounded-poll",
        maximumRefreshMs: 10_000,
        authorization: "workspace",
        fallback: "honest-unavailable",
        fieldGroups: ["application", "repository", "source", "status"],
      },
      {
        id: "application-deployments",
        endpoint: "/applications/{application_id}/deployments",
        transport: "bounded-poll",
        maximumRefreshMs: 10_000,
        authorization: "workspace",
        fallback: "honest-unavailable",
        fieldGroups: ["environment", "cluster", "namespace", "revision"],
      },
      {
        id: "application-gitops-detail",
        endpoint: "/gitops/applications/{application_id}",
        transport: "bounded-poll",
        maximumRefreshMs: 10_000,
        authorization: "workspace",
        fallback: "honest-unavailable",
        fieldGroups: ["scope", "source", "sync", "health", "capabilities"],
      },
      {
        id: "application-drift",
        endpoint: "/applications/{application_id}/drift",
        transport: "bounded-poll",
        maximumRefreshMs: 10_000,
        authorization: "workspace",
        fallback: "honest-unavailable",
        fieldGroups: ["desired", "live", "diff", "observed-at"],
      },
      {
        id: "application-change-events",
        endpoint: "/changes",
        transport: "bounded-poll",
        maximumRefreshMs: 10_000,
        authorization: "workspace",
        fallback: "honest-unavailable",
        fieldGroups: ["event", "application", "severity", "occurred-at"],
      },
      {
        id: "helm-release-detail",
        endpoint: "/helm/releases/{namespace}/{release_name}",
        transport: "bounded-poll",
        maximumRefreshMs: 60_000,
        authorization: "cluster",
        fallback: "honest-unavailable",
        fieldGroups: ["release", "history", "resources", "actions", "refresh-policy"],
      },
      {
        id: "release-plans",
        endpoint: "/release-plans",
        transport: "bounded-poll",
        maximumRefreshMs: 15_000,
        authorization: "workspace",
        fallback: "http-last-known-good",
        fieldGroups: ["plan", "source", "target", "steps"],
      },
      {
        id: "release-runs",
        endpoint: "/release-runs",
        transport: "bounded-poll",
        maximumRefreshMs: 15_000,
        authorization: "workspace",
        fallback: "http-last-known-good",
        fieldGroups: ["run", "status", "steps", "approval", "updated-at"],
      },
      {
        id: "release-plan-detail",
        endpoint: "/release-plans/{plan_id}",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "none",
        fieldGroups: ["plan", "steps", "settings", "revision"],
      },
      {
        id: "release-plan-preview",
        endpoint: "/release-plans/preview",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "none",
        fieldGroups: ["plan", "validation", "changes", "warnings"],
      },
      {
        id: "release-readiness",
        endpoint: "/release-readiness",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "none",
        fieldGroups: ["ready", "checks", "blockers", "coverage"],
      },
      {
        id: "release-plan-start",
        endpoint: "/release-plans/start",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "none",
        fieldGroups: ["run", "status", "steps", "started-at"],
      },
      {
        id: "release-manifest-render",
        endpoint: "/release-plans/render-manifest",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "none",
        fieldGroups: ["manifest", "source", "validation", "step"],
      },
      {
        id: "release-manifest-safe-pr",
        endpoint: "/release-plans/render-manifest/safe-pr",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "none",
        fieldGroups: ["pull-request", "manifest", "source", "step"],
      },
      {
        id: "release-run-advance",
        endpoint: "/release-runs/{run_id}/advance",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "none",
        fieldGroups: ["run", "status", "steps", "reason"],
      },
      {
        id: "release-run-pause",
        endpoint: "/release-runs/{run_id}/pause",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "none",
        fieldGroups: ["run", "status", "reason"],
      },
      {
        id: "release-run-resume",
        endpoint: "/release-runs/{run_id}/resume",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "none",
        fieldGroups: ["run", "status", "reason"],
      },
      {
        id: "release-run-retry",
        endpoint: "/release-runs/{run_id}/retry",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "none",
        fieldGroups: ["run", "status", "reason"],
      },
      {
        id: "release-run-rollback",
        endpoint: "/release-runs/{run_id}/rollback",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "none",
        fieldGroups: ["run", "status", "reason", "rollback"],
      },
      {
        id: "release-run-cancel",
        endpoint: "/release-runs/{run_id}/cancel",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "none",
        fieldGroups: ["run", "status", "reason"],
      },
      {
        id: "release-run-notify",
        endpoint: "/release-runs/{run_id}/notify",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "none",
        fieldGroups: ["run", "status", "notification", "reason"],
      },
    ],
  },
  {
    id: "issues",
    feeds: [
      {
        id: "rca-issues",
        endpoint: "/dashboard/rca/issues",
        transport: "bounded-poll",
        maximumRefreshMs: 10_000,
        authorization: "cluster",
        fallback: "http-last-known-good",
        fieldGroups: ["symptom", "root-cause", "evidence", "recovery", "status"],
      },
      {
        id: "rca-detail",
        endpoint: "/rca/bundles/{correlation_id}",
        transport: "bounded-poll",
        maximumRefreshMs: 4_000,
        authorization: "resource",
        fallback: "http-last-known-good",
        fieldGroups: ["report", "evidence", "plan", "audit", "recent-changes"],
      },
      {
        id: "rca-evidence",
        endpoint: "/evidence",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "resource",
        fallback: "honest-unavailable",
        fieldGroups: ["evidence", "object-reference", "source", "observed-at"],
      },
      {
        id: "rca-evidence-window",
        endpoint: "/evidence/windows/{evidence_key}",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "resource",
        fallback: "honest-unavailable",
        fieldGroups: ["window", "samples", "source", "coverage"],
      },
      {
        id: "rca-reports",
        endpoint: "/rca-reports",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "resource",
        fallback: "honest-unavailable",
        fieldGroups: ["root-cause", "confidence", "evidence-refs", "generated-at"],
      },
      {
        id: "rca-recent-changes",
        endpoint: "/rca/incidents/{incident_id}/recent-changes",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "resource",
        fallback: "honest-unavailable",
        fieldGroups: ["change", "subject", "occurred-at", "relevance"],
      },
      {
        id: "rca-recovery-plan",
        endpoint: "/rca/recovery-plans/by-correlation/{correlation_id}",
        transport: "bounded-poll",
        maximumRefreshMs: 4_000,
        authorization: "resource",
        fallback: "http-last-known-good",
        fieldGroups: ["plan", "actions", "selection", "lifecycle", "outcome"],
      },
      {
        id: "rca-recovery-action-select",
        endpoint: "/rca/recovery-plans/by-correlation/{correlation_id}/actions/select",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "resource",
        fallback: "none",
        fieldGroups: ["plan", "action", "selection", "reason"],
      },
      {
        id: "rca-recovery-retry",
        endpoint: "/rca/recovery-plans/by-correlation/{correlation_id}/retry",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "resource",
        fallback: "none",
        fieldGroups: ["plan", "lifecycle", "retry", "reason"],
      },
      {
        id: "rca-audit",
        endpoint: "/audit/timeline",
        transport: "bounded-poll",
        maximumRefreshMs: 4_000,
        authorization: "resource",
        fallback: "http-last-known-good",
        fieldGroups: ["event", "command", "reason-code", "occurred-at"],
      },
    ],
  },
  {
    id: "timeline",
    feeds: [
      {
        id: "timeline-events",
        endpoint: "/timeline/stream",
        transport: "sse-delta",
        maximumRefreshMs: null,
        authorization: "cluster",
        fallback: "resnapshot-cursor",
        fieldGroups: ["events", "activity", "severity", "coverage", "cursor"],
      },
      {
        id: "timeline-snapshot",
        endpoint: "/timeline/snapshots",
        transport: "sse-snapshot",
        maximumRefreshMs: null,
        authorization: "cluster",
        fallback: "resnapshot-cursor",
        fieldGroups: ["events", "coverage", "cursor", "policy"],
      },
      {
        id: "timeline-capabilities",
        endpoint: "/timeline/capabilities",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "honest-unavailable",
        fieldGroups: ["source-mode", "scope-limit", "stream-policy", "controls"],
      },
      {
        id: "timeline-pins",
        endpoint: "/timeline/pins",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "honest-unavailable",
        fieldGroups: ["pin", "subject", "revision"],
      },
      {
        id: "timeline-overview",
        endpoint: "/timeline/overview",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "cluster",
        fallback: "honest-unavailable",
        fieldGroups: ["activity", "severity", "coverage", "window"],
      },
      {
        id: "timeline-pin-delete",
        endpoint: "/timeline/pins/{pin_id}",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "none",
        fieldGroups: ["pin", "revision", "deletion"],
      },
    ],
  },
  {
    id: "checks",
    feeds: [
      {
        id: "checks-overview",
        endpoint: "/checks/overview",
        transport: "bounded-poll",
        maximumRefreshMs: 30_000,
        authorization: "cluster",
        fallback: "http-last-known-good",
        fieldGroups: ["scope-coverage", "result-availability", "catalog", "reason-codes"],
      },
      {
        id: "checks-detail",
        endpoint: "/checks/{check_id}",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "cluster",
        fallback: "honest-unavailable",
        fieldGroups: ["check", "result", "evidence", "reason-codes"],
      },
    ],
  },
  {
    id: "cost",
    feeds: [
      {
        id: "cost-overview",
        endpoint: "/cost/overview",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "cluster",
        fallback: "honest-unavailable",
        fieldGroups: ["observation", "summary", "reason-codes"],
      },
    ],
  },
  {
    id: "alerts",
    feeds: [
      {
        id: "alert-events",
        endpoint: "/alert-events/stream",
        transport: "sse-delta",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "http-last-known-good",
        fieldGroups: ["event", "rule", "subject", "severity", "delivery", "incident"],
      },
      {
        id: "alert-event-baseline",
        endpoint: "/alert-events",
        transport: "sse-snapshot",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "http-last-known-good",
        fieldGroups: ["event", "rule", "subject", "severity", "status"],
      },
      {
        id: "alert-configuration",
        endpoint: "/alert-rules",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "honest-unavailable",
        fieldGroups: ["rules", "thresholds", "channels", "enabled"],
      },
      {
        id: "alert-channels",
        endpoint: "/alert-channels",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "honest-unavailable",
        fieldGroups: ["channel", "kind", "minimum-severity", "enabled"],
      },
      {
        id: "alert-channel-test",
        endpoint: "/alert-channels/test",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "none",
        fieldGroups: ["channel", "delivery", "result", "reason-code"],
      },
    ],
  },
  {
    id: "ai",
    feeds: [
      {
        id: "ai-conversations",
        endpoint: "/ai/conversations",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "honest-unavailable",
        fieldGroups: ["conversation", "messages", "context", "actions"],
      },
      {
        id: "ai-conversation",
        endpoint: "/ai/conversations/{conversation_id}",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "honest-unavailable",
        fieldGroups: ["conversation", "messages", "context", "status"],
      },
      {
        id: "ai-suggestions",
        endpoint: "/ai/suggestions",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "honest-unavailable",
        fieldGroups: ["suggestion", "prompt", "context"],
      },
      {
        id: "ai-chat",
        endpoint: "/ai/chat",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "none",
        fieldGroups: ["answer", "evidence", "action", "answer-kind"],
      },
      {
        id: "ai-conversation-messages",
        endpoint: "/ai/conversations/{conversation_id}/messages",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "none",
        fieldGroups: ["message", "conversation", "accepted-at"],
      },
    ],
  },
  {
    id: "settings",
    feeds: [
      {
        id: "preferences",
        endpoint: "/settings",
        transport: "mutation-response",
        maximumRefreshMs: null,
        authorization: "session",
        fallback: "honest-unavailable",
        fieldGroups: ["ui-preferences", "revision"],
      },
      {
        id: "access",
        endpoint: "/settings/access",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "workspace",
        fallback: "honest-unavailable",
        fieldGroups: ["roles", "permissions", "scope"],
      },
      {
        id: "refresh-policies",
        endpoint: "/refresh-policies",
        transport: "read-on-open",
        maximumRefreshMs: null,
        authorization: "session",
        fallback: "honest-unavailable",
        fieldGroups: ["cadence", "stale-after", "event-invalidation", "revision"],
      },
    ],
  },
] as const;

/**
 * Runtime API modules imported by each production surface adapter. Tests scan
 * the source tree and fail when a newly used module is not assigned here.
 */
export const SURFACE_API_MODULES: Readonly<Record<ProductSurfaceId, readonly string[]>> = {
  home: [
    "fleet",
    "rca-issues",
    "cost-overview",
    "global-filter",
    "timeline",
  ],
  resources: [
    "cluster-summary",
    "live",
    "inventory-query",
    "inventory-summary",
    "inventory",
    "physical-topology",
    "relation-topology",
    "traffic-overview",
    "node-aliases",
    "config-references",
    "resource-access",
    "resource-manifests",
    "approvals",
    "metrics",
    "usage-series",
    "workload-detail",
  ],
  connect: [
    "cluster-connect",
    "cluster-connection",
    "cluster-registration",
    "github-app",
    "repository-discovery",
    "repository-connection",
  ],
  deploy: [
    "applications",
    "application-catalog",
    "gitops-application-detail",
    "helm-releases",
    "change-timeline",
    "release-flow",
  ],
  issues: [
    "audit-timeline",
    "evidence",
    "rca-bundle",
    "recent-changes",
    "recovery",
  ],
  timeline: ["timeline"],
  checks: ["checks"],
  cost: ["cost-overview"],
  alerts: ["alert-channels", "alert-events", "alert-rules"],
  ai: ["ai-assistant", "ai-conversations"],
  settings: ["settings"],
} as const;

export const SHELL_API_MODULES = ["auth", "clusters"] as const;

/**
 * API adapters whose final path segment is selected from a closed TypeScript
 * union. Static source scanners see a wildcard at that segment; this table
 * makes every permitted concrete backend route explicit and testable.
 */
export const DYNAMIC_API_ROUTE_EXPANSIONS: Readonly<Record<string, readonly string[]>> = {
  "/approvals/{approval_id}/{decision}": [
    "/approvals/{approval_id}/grant",
    "/approvals/{approval_id}/reject",
  ],
  "/clusters/{cluster_id}/inventory/{collection}": [
    "/clusters/{cluster_id}/inventory/resources",
    "/clusters/{cluster_id}/inventory/services",
    "/clusters/{cluster_id}/inventory/workloads",
    "/clusters/{cluster_id}/inventory/resource-detail",
  ],
  "/release-runs/{run_id}/{action}": [
    "/release-runs/{run_id}/advance",
    "/release-runs/{run_id}/pause",
    "/release-runs/{run_id}/resume",
    "/release-runs/{run_id}/retry",
    "/release-runs/{run_id}/rollback",
    "/release-runs/{run_id}/cancel",
    "/release-runs/{run_id}/notify",
  ],
  "/resource-manifests/{resource_id}/{action}": [
    "/resource-manifests/{resource_id}/preview",
    "/resource-manifests/{resource_id}/approve",
    "/resource-manifests/{resource_id}/apply",
  ],
} as const;
