from __future__ import annotations

from packages.config.constants import CommandStatus
from packages.config.settings import env
from packages.contracts.gateway import limits as gateway_limits


class Settings:
    SERVICE_NAME = "api-gateway"
    APP_TITLE = "API Gateway"
    APP_VERSION = "0.1.0"
    ROOT_PATH_ENV = "API_ROOT_PATH"
    DEFAULT_ROOT_PATH = ""
    CONSOLE_ORIGIN_ENV = "CONSOLE_ORIGIN"
    DEFAULT_CONSOLE_ORIGIN = "http://console.management.svc.cluster.local:80"
    FRONTEND_PROXY_TIMEOUT_SECONDS = 10.0
    REALTIME_ORIGIN_ENV = "REALTIME_ORIGIN"
    DEFAULT_REALTIME_ORIGIN = "ws://realtime-gateway.management.svc.cluster.local:8000"

    COMMAND_NOT_FOUND_STATUS_CODE = 404
    CONFLICT_STATUS_CODE = 409
    GATEWAY_ERROR_STATUS_CODE = 500
    SESSION_STORAGE_UNAVAILABLE_STATUS_CODE = 503

    COMMAND_NOT_FOUND_MESSAGE = "command not found"
    DEAD_LETTER_NOT_FOUND_MESSAGE = "dead letter not found"
    DEAD_LETTER_NOT_OPEN_MESSAGE = "dead letter is not open"
    DEAD_LETTER_REPLAYED_MESSAGE = "dead letter already replayed"
    GATEWAY_ERROR_MESSAGE = "internal server error"

    COMMAND_STATUS_QUEUED = CommandStatus.QUEUED
    COMMAND_STATUS_LEASED = CommandStatus.LEASED
    COMMAND_STATUS_RUNNING = CommandStatus.RUNNING
    EVENT_STREAM_MEDIA_TYPE = "text/event-stream"
    DEFAULT_DEAD_LETTER_LIMIT = gateway_limits.DEAD_LETTER_DEFAULT_LIMIT
    MAX_DEAD_LETTER_LIMIT = gateway_limits.DEAD_LETTER_MAX_LIMIT
    # 브라우저 SPA CORS — 쿠키 인증 요청 허용 origin(콤마 구분). 로컬 개발 origin 기본 포함.
    CORS_ALLOW_ORIGINS_ENV = "CORS_ALLOW_ORIGINS"
    DEFAULT_CORS_ALLOW_ORIGINS = (
        "http://localhost:5173,http://localhost:4173,http://127.0.0.1:5173,http://127.0.0.1:4173"
    )
    CSRF_INTENT_HEADER = "x-service-csrf"
    CSRF_INTENT_VALUE = "same-origin"
    CSRF_REJECT_MESSAGE = "same-origin session request required"
    REDIS_URL_ENV = "REDIS_URL"
    SESSION_TTL_ENV = "SESSION_TTL_SECONDS"
    SESSION_KEY_PREFIX = "session"
    RATE_LIMIT_KEY_PREFIX = "rate"
    AUTH_ABUSE_RATE_WINDOW_SECONDS_ENV = (
        "AUTH_ABUSE_RATE_WINDOW_SECONDS"  # 인증 남용 계수 윈도 초(기본 900)
    )
    AUTH_ABUSE_RATE_WINDOW_SECONDS = int(env(AUTH_ABUSE_RATE_WINDOW_SECONDS_ENV, str(15 * 60)))
    AUTH_ABUSE_FIRST_LOCK_SECONDS_ENV = "AUTH_ABUSE_FIRST_LOCK_SECONDS"  # 1차 잠금 초(기본 900)
    AUTH_ABUSE_FIRST_LOCK_SECONDS = int(env(AUTH_ABUSE_FIRST_LOCK_SECONDS_ENV, str(15 * 60)))
    AUTH_ABUSE_SECOND_LOCK_SECONDS_ENV = "AUTH_ABUSE_SECOND_LOCK_SECONDS"  # 2차 잠금 초(기본 3600)
    AUTH_ABUSE_SECOND_LOCK_SECONDS = int(env(AUTH_ABUSE_SECOND_LOCK_SECONDS_ENV, str(60 * 60)))
    AUTH_ABUSE_THIRD_LOCK_SECONDS_ENV = "AUTH_ABUSE_THIRD_LOCK_SECONDS"  # 3차 잠금 초(기본 86400)
    AUTH_ABUSE_THIRD_LOCK_SECONDS = int(env(AUTH_ABUSE_THIRD_LOCK_SECONDS_ENV, str(24 * 60 * 60)))
    AUTH_ABUSE_STRIKE_TTL_SECONDS_ENV = (
        "AUTH_ABUSE_STRIKE_TTL_SECONDS"  # 누적 스트라이크 TTL 초(기본 86400)
    )
    AUTH_ABUSE_STRIKE_TTL_SECONDS = int(env(AUTH_ABUSE_STRIKE_TTL_SECONDS_ENV, str(24 * 60 * 60)))
    SIGNUP_EMAIL_RATE_LIMIT_ENV = "SIGNUP_EMAIL_RATE_LIMIT"  # 가입 이메일별 한도(기본 3)
    SIGNUP_EMAIL_RATE_LIMIT = int(env(SIGNUP_EMAIL_RATE_LIMIT_ENV, "3"))
    SIGNUP_IP_RATE_LIMIT_ENV = "SIGNUP_IP_RATE_LIMIT"  # 가입 IP별 한도(기본 20)
    SIGNUP_IP_RATE_LIMIT = int(env(SIGNUP_IP_RATE_LIMIT_ENV, "20"))
    LOGIN_EMAIL_RATE_LIMIT_ENV = "LOGIN_EMAIL_RATE_LIMIT"  # 로그인 이메일별 한도(기본 10)
    LOGIN_EMAIL_RATE_LIMIT = int(env(LOGIN_EMAIL_RATE_LIMIT_ENV, "10"))
    LOGIN_IP_RATE_LIMIT_ENV = "LOGIN_IP_RATE_LIMIT"  # 로그인 IP별 한도(기본 60)
    LOGIN_IP_RATE_LIMIT = int(env(LOGIN_IP_RATE_LIMIT_ENV, "60"))
    RESEND_EMAIL_RATE_LIMIT = SIGNUP_EMAIL_RATE_LIMIT
    RESEND_IP_RATE_LIMIT = SIGNUP_IP_RATE_LIMIT
    CHECK_EMAIL_EMAIL_RATE_LIMIT_ENV = "CHECK_EMAIL_EMAIL_RATE_LIMIT"
    CHECK_EMAIL_EMAIL_RATE_LIMIT = int(env(CHECK_EMAIL_EMAIL_RATE_LIMIT_ENV, "20"))
    CHECK_EMAIL_IP_RATE_LIMIT_ENV = "CHECK_EMAIL_IP_RATE_LIMIT"
    CHECK_EMAIL_IP_RATE_LIMIT = int(env(CHECK_EMAIL_IP_RATE_LIMIT_ENV, "120"))
    RESEND_EMAIL_COOLDOWN_SECONDS_ENV = "RESEND_EMAIL_COOLDOWN_SECONDS"
    RESEND_EMAIL_COOLDOWN_SECONDS = int(env(RESEND_EMAIL_COOLDOWN_SECONDS_ENV, "60"))
    EMAIL_VERIFICATION_KEY_PREFIX = "email_verify"
    EMAIL_VERIFICATION_TTL_SECONDS_ENV = (
        "EMAIL_VERIFICATION_TTL_SECONDS"  # 인증 토큰 TTL 초(기본 3600)
    )
    EMAIL_VERIFICATION_TTL_SECONDS = int(env(EMAIL_VERIFICATION_TTL_SECONDS_ENV, str(60 * 60)))
    EMAIL_VERIFICATION_TOKEN_BYTES = 32
    SESSION_TOKEN_BYTES = 32
    DEFAULT_RATE_LIMIT_ENV = "DEFAULT_RATE_LIMIT"  # 세션 공통 레이트리밋 횟수(기본 120)
    DEFAULT_RATE_LIMIT = int(env(DEFAULT_RATE_LIMIT_ENV, "120"))
    RATE_LIMIT_WINDOW_SECONDS_ENV = "RATE_LIMIT_WINDOW_SECONDS"  # 레이트리밋 윈도 초(기본 60)
    RATE_LIMIT_WINDOW_SECONDS = int(env(RATE_LIMIT_WINDOW_SECONDS_ENV, "60"))
    AUTHENTICATED_READ_RATE_LIMIT_ENV = "AUTHENTICATED_READ_RATE_LIMIT"
    AUTHENTICATED_READ_RATE_LIMIT = int(env(AUTHENTICATED_READ_RATE_LIMIT_ENV, "600"))
    AUTHENTICATED_READ_RATE_WINDOW_SECONDS_ENV = "AUTHENTICATED_READ_RATE_WINDOW_SECONDS"
    AUTHENTICATED_READ_RATE_WINDOW_SECONDS = int(
        env(AUTHENTICATED_READ_RATE_WINDOW_SECONDS_ENV, "60")
    )
    AUTHENTICATED_MUTATION_SESSION_RATE_LIMIT_ENV = "AUTHENTICATED_MUTATION_SESSION_RATE_LIMIT"
    AUTHENTICATED_MUTATION_SESSION_RATE_LIMIT = int(
        env(AUTHENTICATED_MUTATION_SESSION_RATE_LIMIT_ENV, "30")
    )
    AUTHENTICATED_MUTATION_USER_RATE_LIMIT_ENV = "AUTHENTICATED_MUTATION_USER_RATE_LIMIT"
    AUTHENTICATED_MUTATION_USER_RATE_LIMIT = int(
        env(AUTHENTICATED_MUTATION_USER_RATE_LIMIT_ENV, "60")
    )
    AUTHENTICATED_MUTATION_RATE_WINDOW_SECONDS_ENV = "AUTHENTICATED_MUTATION_RATE_WINDOW_SECONDS"
    AUTHENTICATED_MUTATION_RATE_WINDOW_SECONDS = int(
        env(AUTHENTICATED_MUTATION_RATE_WINDOW_SECONDS_ENV, "60")
    )
    AUTHORIZATION_HEADER = "authorization"
    BEARER_PREFIX = "bearer "
    SESSION_TOKEN_HEADER = "x-session-token"
    METRICS_TOKEN_ENV = "METRICS_TOKEN"  # 설정 시 /metrics 에 Bearer 강제
    METRICS_TOKEN_NOT_CONFIGURED_MESSAGE = "metrics token is not configured"
    RATE_LIMIT_EXCEEDED_MESSAGE = "요청이 너무 많습니다. 잠시 후 다시 시도해 주세요."
    AUTHENTICATION_REQUIRED_MESSAGE = "authentication required"
    WORKSPACE_ACCESS_DENIED_MESSAGE = "workspace access denied"
    SESSION_STORAGE_UNAVAILABLE_MESSAGE = "session storage unavailable"
    REDIS_NOT_CONNECTED_MESSAGE = "Redis session store is not connected"
    INVALID_CREDENTIALS_MESSAGE = "invalid email or password"
    EMAIL_VERIFICATION_REQUIRED_MESSAGE = "email verification required"
    EMAIL_VERIFICATION_INVALID_MESSAGE = "invalid or expired email verification token"
    ACCOUNT_APPROVAL_REQUIRED_MESSAGE = "account approval required"
    PASSWORD_CONFIRMATION_MISMATCH_MESSAGE = "password confirmation does not match"
    USER_ALREADY_EXISTS_MESSAGE = "user already exists"
    USER_NOT_FOUND_MESSAGE = "user not found"
