from __future__ import annotations

from enum import StrEnum


class Gateway(StrEnum):
    """Gateway 요청/응답·payload의 필드 이름.

    StrEnum 이라 dict 인덱싱(d[Gateway.STATUS])과 json 직렬화에서
    문자열 값으로 자동 동작.
    """

    ACCEPTED = "accepted"
    ACTION = "action"
    AGENT_ID = "agent_id"
    APPLIED = "applied"
    APPROVAL_DECIDED_BY = "approval_decided_by"
    APPROVAL_EXPIRES_AT = "approval_expires_at"
    APPROVAL_REF = "approval_ref"
    ATTEMPT_ID = "attempt_id"
    ACTOR = "actor"
    AUTHENTICATED = "authenticated"
    CAPABILITIES = "capabilities"
    CANCEL_GENERATION = "cancel_generation"
    CANCEL_REQUESTED = "cancel_requested"
    CARDS = "cards"
    CLUSTER_ID = "cluster_id"
    COMMAND = "command"
    COMMAND_ID = "command_id"
    CORRELATION_ID = "correlation_id"
    DEAD_LETTER_ID = "dead_letter_id"
    DEAD_LETTERS = "dead_letters"
    DIRECT_EXECUTION = "direct_execution"
    DIRECT_EXECUTION_CONFIRMED = "direct_execution_confirmed"
    DUPLICATE = "duplicate"
    EVIDENCE_KEY = "evidence_key"
    ERROR = "error"
    EVENT = "event"
    EVENT_ID = "event_id"
    FAILURE_POLICY = "failure_policy"
    JOB = "job"
    JOB_ID = "job_id"
    EMAIL = "email"
    LEASED = "leased"
    LEASED_UNTIL = "leased_until"
    LEASE_ID = "lease_id"
    MESSAGE = "message"
    NAMESPACE = "namespace"
    PAYLOAD = "payload"
    PROVIDER_KEY = "provider_key"
    PROVIDER_KEYS = "provider_keys"
    PROVIDER_POLICY = "provider_policy"
    POLICY_GENERATION = "policy_generation"
    POLICY_DECISION_REF = "policy_decision_ref"
    REPLAY_EVENT = "replay_event"
    REQUESTED_BY = "requested_by"
    RESULT = "result"
    RESOURCES = "resources"
    RETRYABLE = "retryable"
    ROLES = "roles"
    SERVICE = "service"
    SOURCE_ID = "source_id"
    SESSION = "session"
    SESSION_TOKEN = "session_token"
    STATUS = "status"
    STATUS_ARCHIVED = "archived"
    STATUS_OK = "ok"
    STATUS_OPEN = "open"
    STATUS_READY = "ready"
    STATUS_REPLAYED = "replayed"
    STDERR = "stderr"
    STDOUT = "stdout"
    USER_ID = "user_id"
    VERIFICATION_REQUIRED = "verification_required"
    WINDOW_START = "window_start"
    WORKSPACE_ID = "workspace_id"
