"""Shared Gateway API bounds used by routers and conservative clients."""

from __future__ import annotations

CLUSTER_LIST_DEFAULT_LIMIT = 100
CLUSTER_LIST_MAX_LIMIT = 200
CLUSTER_ID_MAX_LENGTH = 512
KUBERNETES_NAME_MAX_LENGTH = 253
CORRELATION_ID_MAX_LENGTH = 2048
INCIDENT_ID_MAX_LENGTH = 2048

INVENTORY_RESOURCE_DEFAULT_LIMIT = 200
INVENTORY_RESOURCE_MAX_LIMIT = 1000
CONFIG_REFERENCE_REASON_CODE_MAX_COUNT = 16
INVENTORY_RELATED_DEFAULT_LIMIT = 100
INVENTORY_RELATED_MAX_LIMIT = 1000
INVENTORY_EVENT_DEFAULT_LIMIT = 50
INVENTORY_EVENT_MAX_LIMIT = 200
CLUSTER_USAGE_DEFAULT_LIMIT = 288
CLUSTER_USAGE_MAX_LIMIT = 2000
FILTER_FACET_DEFAULT_LIMIT = 50
FILTER_FACET_MAX_LIMIT = 200
GLOBAL_FILTER_FACET_DEFAULT_LIMIT = 8
GLOBAL_FILTER_FACET_MAX_LIMIT = 20
FILTER_CURSOR_MAX_LENGTH = 8192
FILTER_AXIS_MAX_VALUES = 100
FILTER_AXIS_VALUE_MAX_LENGTH = 253
FILTER_LABEL_SELECTOR_MAX_VALUES = 24
FILTER_LABEL_VALUE_MAX_LENGTH = 1024
FILTER_SEARCH_MAX_LENGTH = 200
FILTER_VALUE_LIST_MAX_LENGTH = 2048
KUBERNETES_LABEL_NAME_MAX_LENGTH = 63
KUBERNETES_LABEL_PREFIX_MAX_LENGTH = 253
RESOURCE_METRIC_HISTORY_DEFAULT_LIMIT = 60
RESOURCE_METRIC_HISTORY_MAX_LIMIT = 288
RESOURCE_METRIC_HISTORY_MAX_IDS = 100
RESOURCE_METRIC_HISTORY_ID_MAX_LENGTH = 512
RESOURCE_METRIC_HISTORY_IDS_MAX_QUERY_LENGTH = 8192
RESOURCE_METRIC_HISTORY_DEFAULT_RANGE = "1h"
RESOURCE_METRIC_HISTORY_RANGE_SECONDS = {
    "15m": 15 * 60,
    "1h": 60 * 60,
    "6h": 6 * 60 * 60,
    "24h": 24 * 60 * 60,
}
RESOURCE_METRIC_HISTORY_RANGES = tuple(RESOURCE_METRIC_HISTORY_RANGE_SECONDS)

RESOURCE_GRAPH_DEFAULT_NODE_LIMIT = 200
RESOURCE_GRAPH_MAX_NODE_LIMIT = 200
RESOURCE_GRAPH_DEFAULT_EDGE_LIMIT = 1000
RESOURCE_GRAPH_MAX_EDGE_LIMIT = 2000

DEAD_LETTER_DEFAULT_LIMIT = 50
DEAD_LETTER_MAX_LIMIT = 100

DASHBOARD_RCA_DEFAULT_LIMIT = 50
DASHBOARD_RCA_MAX_LIMIT = 100
RESOURCE_ISSUE_DEFAULT_LIMIT = 25

RCA_QUERY_DEFAULT_LIMIT = 50
RCA_QUERY_MAX_LIMIT = 200
RCA_RECENT_CHANGE_DEFAULT_LIMIT = 5
RCA_RECENT_CHANGE_MAX_LIMIT = 50

ALERT_EVENT_DEFAULT_LIMIT = 100
ALERT_EVENT_MAX_LIMIT = 200

AUDIT_TIMELINE_DEFAULT_LIMIT = 50
AUDIT_TIMELINE_MAX_LIMIT = 200

APPLICATION_LIST_DEFAULT_LIMIT = 100
APPLICATION_LIST_MAX_LIMIT = 200
APPLICATION_DEPLOYMENT_DEFAULT_LIMIT = 100
APPLICATION_DEPLOYMENT_MAX_LIMIT = 500
APPLICATION_WORKFLOW_RUN_DEFAULT_LIMIT = 100
APPLICATION_WORKFLOW_RUN_MAX_LIMIT = 500

RELEASE_PLAN_DEFAULT_LIMIT = 100
RELEASE_PLAN_MAX_LIMIT = 500
RELEASE_RUN_DEFAULT_LIMIT = 50
RELEASE_RUN_MAX_LIMIT = 200
RELEASE_RUN_SUMMARY_LIMIT = 200
RELEASE_AUDIT_DEFAULT_LIMIT = 200
RELEASE_AUDIT_EXPORT_DEFAULT_LIMIT = 500
RELEASE_AUDIT_MAX_LIMIT = 1000

CHANGE_TIMELINE_MIN_BUCKET_MS = 1_000
CHANGE_TIMELINE_MAX_BUCKET_MS = 3_600_000
CHANGE_TIMELINE_MAX_RANGE_MS = 24 * 60 * 60 * 1_000
CHANGE_TIMELINE_MAX_BUCKETS = 1_440
CHANGE_TIMELINE_MAX_EPOCH_MS = 253_402_300_799_000
