kind: Service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8001
    protocol: TCP
    targetPort: http
  selector:
    app: game-server
    opsia.dev/fleet: canary
    opsia.dev/room-id: canary-room
metadata:
  name: game-room-canary
  labels:
    app: game-server
    opsia.dev/fleet: canary
    opsia.dev/public: disabled
  namespace: sandbox
apiVersion: v1
