global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: metrics-source
    static_configs:
      - targets: ["metrics-source:9200"]
  - job_name: pushgateway
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]
